on:
  # Actions upon pull
  pull_request: 
  # Actions upon push: this says to only run the ci/cd to pushes on main
  push:
    branches:
      - main
      
jobs:
  # This can be any name you want, we'll call it "tests"
  tests: 
    # Pick an operating system
    runs-on: ubuntu-latest
    steps:
      # See https://github.com/actions/checkout. These are actually GitHub repositories
      # "This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - uses: actions/checkout@v3
      
      # You can set up things specific to a single action with "with:"
      - uses: actions/setup-python@v4
        with: 
          python-version: "3.11"
          
      # The second type of possible action. 
      - name: Install packagae and test requirements
        run: python -m pip install .[test]

      
