on:
  # Actions upon pull
  pull_request: 
  # Actions upon push: this says to only run the ci/cd to pushes on main
  push:
    branches:
      - main
      
jobs:
  # This can be any name you want, we'll call it "tests"
  tests: 
    # Use substitution since we have a matrix: access the key that we called runs-on
    name: Test ${{ matrix.runs-on }}
  
    runs-on: ${{ matrix.runs-on }}
    
    # Matrix: setting up multiple runs
    strategy:
      
      fail-fast: false 
      
      matrix: 
        # We will name the key based on what we want to fill it with, but this isn't required
        runs-on: 
          # Inside this we want a list
          - ubuntu-latest
          - windows-latest
    
    steps:
      # See https://github.com/actions/checkout. These are actually GitHub repositories
      # "This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - uses: actions/checkout@v3
      
      # You can set up things specific to a single action with "with:"
      - uses: actions/setup-python@v4
        with: 
          python-version: "3.11"
          
      # The second type of possible action. 
      - name: Install package and test requirements
        run: python -m pip install .[test]

      
